-- MySQL Script generated by MySQL Workbench
-- Fri Jun 14 17:02:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produccion` (
  `idProduccion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SemblanzaCom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SemblanzaCom` (
  `idSemblanzaCom` INT NOT NULL,
  `SemCom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSemblanzaCom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`logotipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`logotipos` (
  `idlogotipos` INT NOT NULL,
  `Opcion` TINYINT NOT NULL,
  PRIMARY KEY (`idlogotipos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fotografias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fotografias` (
  `idFotografias` INT NOT NULL,
  `Opcion` TINYINT NOT NULL,
  PRIMARY KEY (`idFotografias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProgramaMano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProgramaMano` (
  `idProgramaMano` INT NOT NULL,
  `Opcion` TINYINT NOT NULL,
  PRIMARY KEY (`idProgramaMano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RequerimientosTec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RequerimientosTec` (
  `idRequerimientostec` INT NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRequerimientostec`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SemblanzaAct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SemblanzaAct` (
  `idSemblanzaAct` INT NOT NULL,
  `SemAct` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSemblanzaAct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lugar` (
  `idLugar` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLugar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagos` (
  `idPagos` INT NOT NULL,
  `Requerimiento` VARCHAR(25) NOT NULL,
  `DocumentacionOkey` DATE NOT NULL,
  `FechaPago` DATE NOT NULL,
  PRIMARY KEY (`idPagos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cortesia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cortesia` (
  `idCortesia` INT NOT NULL,
  `Costo` FLOAT NOT NULL,
  PRIMARY KEY (`idCortesia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrada` (
  `idEntrada` INT NOT NULL,
  `EntradaLibre` TINYINT NOT NULL,
  `Cortesia_idCortesia` INT NOT NULL,
  PRIMARY KEY (`idEntrada`, `Cortesia_idCortesia`),
  INDEX `fk_Entrada_Cortesia1_idx` (`Cortesia_idCortesia` ASC),
  CONSTRAINT `fk_Entrada_Cortesia1`
    FOREIGN KEY (`Cortesia_idCortesia`)
    REFERENCES `mydb`.`Cortesia` (`idCortesia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Difusion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Difusion` (
  `idDifusion` INT NOT NULL,
  `FechadeInicio` DATE NOT NULL,
  PRIMARY KEY (`idDifusion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transporte` (
  `idTransporte` INT NOT NULL,
  `Opcion` TINYINT NOT NULL,
  PRIMARY KEY (`idTransporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actividad` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `Lugar_idLugar` INT NOT NULL,
  `Produccion_idProduccion` INT NOT NULL,
  `SemblanzaCom_idSemblanzaCom` INT NOT NULL,
  `logotipos_idlogotipos` INT NOT NULL,
  `Fotografias_idFotografias` INT NOT NULL,
  `ProgramaMano_idProgramaMano` INT NOT NULL,
  `RequerimientosTec_idRequerimientostec` INT NOT NULL,
  `SemblanzaAct_idSemblanzaAct` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Duracion` TIME NOT NULL,
  `Fecha` DATE NOT NULL,
  `Pagos_idPagos` INT NOT NULL,
  `Entrada_idEntrada` INT NOT NULL,
  `Entrada_Cortesia_idCortesia` INT NOT NULL,
  `Difusion_idDifusion` INT NOT NULL,
  `Transporte_idTransporte` INT NOT NULL,
  PRIMARY KEY (`idActividad`, `Lugar_idLugar`, `Produccion_idProduccion`, `SemblanzaCom_idSemblanzaCom`, `logotipos_idlogotipos`, `Fotografias_idFotografias`, `ProgramaMano_idProgramaMano`, `RequerimientosTec_idRequerimientostec`, `SemblanzaAct_idSemblanzaAct`, `Pagos_idPagos`, `Entrada_idEntrada`, `Entrada_Cortesia_idCortesia`, `Difusion_idDifusion`, `Transporte_idTransporte`),
  INDEX `fk_Actividad_Produccion_idx` (`Produccion_idProduccion` ASC),
  INDEX `fk_Actividad_SemblanzaCom1_idx` (`SemblanzaCom_idSemblanzaCom` ASC),
  INDEX `fk_Actividad_logotipos1_idx` (`logotipos_idlogotipos` ASC),
  INDEX `fk_Actividad_Fotografias1_idx` (`Fotografias_idFotografias` ASC),
  INDEX `fk_Actividad_ProgramaMano1_idx` (`ProgramaMano_idProgramaMano` ASC),
  INDEX `fk_Actividad_RequerimientosTec1_idx` (`RequerimientosTec_idRequerimientostec` ASC),
  INDEX `fk_Actividad_SemblanzaAct1_idx` (`SemblanzaAct_idSemblanzaAct` ASC),
  INDEX `fk_Actividad_Lugar1_idx` (`Lugar_idLugar` ASC),
  INDEX `fk_Actividad_Pagos1_idx` (`Pagos_idPagos` ASC),
  INDEX `fk_Actividad_Entrada1_idx` (`Entrada_idEntrada` ASC, `Entrada_Cortesia_idCortesia` ASC),
  INDEX `fk_Actividad_Difusion1_idx` (`Difusion_idDifusion` ASC),
  INDEX `fk_Actividad_Transporte1_idx` (`Transporte_idTransporte` ASC),
  CONSTRAINT `fk_Actividad_Produccion`
    FOREIGN KEY (`Produccion_idProduccion`)
    REFERENCES `mydb`.`Produccion` (`idProduccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_SemblanzaCom1`
    FOREIGN KEY (`SemblanzaCom_idSemblanzaCom`)
    REFERENCES `mydb`.`SemblanzaCom` (`idSemblanzaCom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_logotipos1`
    FOREIGN KEY (`logotipos_idlogotipos`)
    REFERENCES `mydb`.`logotipos` (`idlogotipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Fotografias1`
    FOREIGN KEY (`Fotografias_idFotografias`)
    REFERENCES `mydb`.`Fotografias` (`idFotografias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_ProgramaMano1`
    FOREIGN KEY (`ProgramaMano_idProgramaMano`)
    REFERENCES `mydb`.`ProgramaMano` (`idProgramaMano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_RequerimientosTec1`
    FOREIGN KEY (`RequerimientosTec_idRequerimientostec`)
    REFERENCES `mydb`.`RequerimientosTec` (`idRequerimientostec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_SemblanzaAct1`
    FOREIGN KEY (`SemblanzaAct_idSemblanzaAct`)
    REFERENCES `mydb`.`SemblanzaAct` (`idSemblanzaAct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Lugar1`
    FOREIGN KEY (`Lugar_idLugar`)
    REFERENCES `mydb`.`Lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Pagos1`
    FOREIGN KEY (`Pagos_idPagos`)
    REFERENCES `mydb`.`Pagos` (`idPagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Entrada1`
    FOREIGN KEY (`Entrada_idEntrada` , `Entrada_Cortesia_idCortesia`)
    REFERENCES `mydb`.`Entrada` (`idEntrada` , `Cortesia_idCortesia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Difusion1`
    FOREIGN KEY (`Difusion_idDifusion`)
    REFERENCES `mydb`.`Difusion` (`idDifusion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Transporte1`
    FOREIGN KEY (`Transporte_idTransporte`)
    REFERENCES `mydb`.`Transporte` (`idTransporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diseñador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diseñador` (
  `idDiseñador` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDiseñador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`viñeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viñeta` (
  `idviñeta` INT NOT NULL,
  `Opcion` TINYINT NOT NULL,
  PRIMARY KEY (`idviñeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartel` (
  `idCarte` INT NOT NULL,
  `Opcion` TINYINT NOT NULL,
  PRIMARY KEY (`idCarte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CartelWeb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CartelWeb` (
  `idCartelWeb` INT NOT NULL,
  `Opcion` TINYINT NOT NULL,
  PRIMARY KEY (`idCartelWeb`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Invitacion` (
  `idInvitacion` INT NOT NULL,
  `Opcion` TINYINT NOT NULL,
  PRIMARY KEY (`idInvitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Corrector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Corrector` (
  `idCorrector` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCorrector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Correcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Correcion` (
  `idCorrecion` INT NOT NULL,
  `Entrega` DATE NOT NULL,
  `Devolucion` DATE NOT NULL,
  `Corrector_idCorrector` INT NOT NULL,
  PRIMARY KEY (`idCorrecion`, `Corrector_idCorrector`),
  INDEX `fk_Correcion_Corrector1_idx` (`Corrector_idCorrector` ASC),
  CONSTRAINT `fk_Correcion_Corrector1`
    FOREIGN KEY (`Corrector_idCorrector`)
    REFERENCES `mydb`.`Corrector` (`idCorrector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diseño`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diseño` (
  `idDiseño` INT NOT NULL,
  `Diseñador_idDiseñador` INT NOT NULL,
  `Fotografias_idFotografias` INT NOT NULL,
  `viñeta_idviñeta` INT NOT NULL,
  `logotipos_idlogotipos` INT NOT NULL,
  `Lugar_idLugar` INT NOT NULL,
  `Carte_idCarte` INT NOT NULL,
  `CartelWeb_idCartelWeb` INT NOT NULL,
  `Cortesia_idCortesia` INT NOT NULL,
  `ProgramaMano_idProgramaMano` INT NOT NULL,
  `Invitacion_idInvitacion` INT NOT NULL,
  `FechaEntregaInfo` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Leyenda` VARCHAR(45) NOT NULL,
  `Entrega` DATE NOT NULL,
  `EntregaImpresionDig` DATE NOT NULL,
  `EntregaImpresionOff` DATE NOT NULL,
  `EntregaSerigrafia` DATE NOT NULL,
  `EntregaProgramamano` DATE NOT NULL,
  `EntregaInvitacion` DATE NOT NULL,
  `EntregaVolante` DATE NOT NULL,
  `Correcion_idCorrecion` INT NOT NULL,
  PRIMARY KEY (`idDiseño`, `Diseñador_idDiseñador`, `Fotografias_idFotografias`, `viñeta_idviñeta`, `logotipos_idlogotipos`, `Lugar_idLugar`, `Carte_idCarte`, `CartelWeb_idCartelWeb`, `Cortesia_idCortesia`, `ProgramaMano_idProgramaMano`, `Invitacion_idInvitacion`, `Correcion_idCorrecion`),
  INDEX `fk_Diseño_Diseñador1_idx` (`Diseñador_idDiseñador` ASC),
  INDEX `fk_Diseño_Fotografias1_idx` (`Fotografias_idFotografias` ASC),
  INDEX `fk_Diseño_viñeta1_idx` (`viñeta_idviñeta` ASC),
  INDEX `fk_Diseño_logotipos1_idx` (`logotipos_idlogotipos` ASC),
  INDEX `fk_Diseño_Lugar1_idx` (`Lugar_idLugar` ASC),
  INDEX `fk_Diseño_Carte1_idx` (`Carte_idCarte` ASC),
  INDEX `fk_Diseño_CartelWeb1_idx` (`CartelWeb_idCartelWeb` ASC),
  INDEX `fk_Diseño_Cortesia1_idx` (`Cortesia_idCortesia` ASC),
  INDEX `fk_Diseño_ProgramaMano1_idx` (`ProgramaMano_idProgramaMano` ASC),
  INDEX `fk_Diseño_Invitacion1_idx` (`Invitacion_idInvitacion` ASC),
  INDEX `fk_Diseño_Correcion1_idx` (`Correcion_idCorrecion` ASC),
  CONSTRAINT `fk_Diseño_Diseñador1`
    FOREIGN KEY (`Diseñador_idDiseñador`)
    REFERENCES `mydb`.`Diseñador` (`idDiseñador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseño_Fotografias1`
    FOREIGN KEY (`Fotografias_idFotografias`)
    REFERENCES `mydb`.`Fotografias` (`idFotografias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseño_viñeta1`
    FOREIGN KEY (`viñeta_idviñeta`)
    REFERENCES `mydb`.`viñeta` (`idviñeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseño_logotipos1`
    FOREIGN KEY (`logotipos_idlogotipos`)
    REFERENCES `mydb`.`logotipos` (`idlogotipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseño_Lugar1`
    FOREIGN KEY (`Lugar_idLugar`)
    REFERENCES `mydb`.`Lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseño_Carte1`
    FOREIGN KEY (`Carte_idCarte`)
    REFERENCES `mydb`.`Cartel` (`idCarte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseño_CartelWeb1`
    FOREIGN KEY (`CartelWeb_idCartelWeb`)
    REFERENCES `mydb`.`CartelWeb` (`idCartelWeb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseño_Cortesia1`
    FOREIGN KEY (`Cortesia_idCortesia`)
    REFERENCES `mydb`.`Cortesia` (`idCortesia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseño_ProgramaMano1`
    FOREIGN KEY (`ProgramaMano_idProgramaMano`)
    REFERENCES `mydb`.`ProgramaMano` (`idProgramaMano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseño_Invitacion1`
    FOREIGN KEY (`Invitacion_idInvitacion`)
    REFERENCES `mydb`.`Invitacion` (`idInvitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseño_Correcion1`
    FOREIGN KEY (`Correcion_idCorrecion`)
    REFERENCES `mydb`.`Correcion` (`idCorrecion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Contraseña` VARCHAR(15) NOT NULL,
  `Administrador` TINYINT NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
